# Generated by Django 5.1.7 on 2025-03-24 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcase',
            name='expected_output',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='input_value',
            field=models.JSONField(),
        ),
    ]
