# Generated by Django 5.1.7 on 2025-03-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_alter_testcase_expected_output_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solution_code',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
