# Generated by Django 5.1.6 on 2025-03-28 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_problem_solution_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='function_header',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='problem',
            name='input_vars',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='problem',
            name='return_type',
            field=models.CharField(default='None', max_length=50),
        ),
    ]
